AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Roman Numerals Converter Application. This template creates Python Flask Web Application on 
  Amazon Linux 2 (ami-033b95fb8079dc481) EC2 Instance with custom security group allowing http connections on port 80 and SSH 
  connection on port 22. Roman Numerals Converter Application is downloaded from Github repository, then installed on Flask.

Parameters:
  MorgoKP:
    Description: Select your key
    Type: AWS::EC2::KeyPair::KeyName
  
Resources:

  MorgoInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref MorgoKP
      ImageId: ami-033b95fb8079dc481
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MorgoSG
      UserData: !Base64 |
        #!/bin/bash

        yum update -y
        yum install python3 -y
        pip3 install flask
        cd /home/ec2-user
        wget https://raw.githubusercontent.com/Morgoliath/my-projects/main/AWS/Roman-Numerals-Converter/app.py
        mkdir templates
        cd templates
        wget https://raw.githubusercontent.com/Morgoliath/my-projects/main/AWS/Roman-Numerals-Converter/templates/index.html
        wget https://raw.githubusercontent.com/Morgoliath/my-projects/main/AWS/Roman-Numerals-Converter/templates/result.html
        cd ..
        python3 app.py
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
  MorgoSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: For the instance that allows ssh and http
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  
Outputs:
  MorgoURL:
    Description: Url of Roman-Numeral-Converter
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MorgoInstance.PublicDnsName
