AWSTemplateFormatVersion: 2010-09-09
Description: |
  This stack, ask user for a key pair. Opens new instance with t2.micro but it can be configured by user also. AMI will be the latest one
Parameters:
  
  MorgoKP:
    Description: Choose your key
    Type: AWS::EC2::KeyPair::KeyName

  MorgoIT:
    Description: Choose your instance.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.nano
      - t2.nano
      - t1.micro
      - t2.micro
      - t4g.nano
      - t4g.micro
      - t4g.small
      - t4g.medium
  
Resources:
  
  MorgoInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-033b95fb8079dc481
      InstanceType: !Ref MorgoIT
      KeyName: !Ref MorgoKP
      SecurityGroupIds:
        - !Ref MorgoSG
      Tags:
        - Key: "Name"
          Value: "Web Server of StackName"
      UserData: !Base64 |
        #!/bin/bash

          yum update -y
          yum install -y httpd
          FOLDER="https://raw.githubusercontent.com/Morgoliath/my-projects/main/AWS/Roman-Numerals-Converter"
          cd /var/www/html
          wget $FOLDER/templates/index.html
          wget $FOLDER/templates/result.html
          cd ..
          wget $FOLDER/app.py
          python3 app.py
          cd ~
          sudo yum remove awscli -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo yum install unzip
          unzip awscliv2.zip 
          sudo ./aws/install
          export PATH=$PATH:/usr/local/bin/aws
          aws configure set aws_access_key_id AKIAY5D7NSXTKSQ3K6P2
          aws configure set aws_secret_access_key 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
          aws configure set default.region us-west-2
          aws ec2 run-instances --image-id $(aws ssm get-parameters --names /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2 --query 
          'Parameters[0].[Value]' --output text) --instance-type t2.micro --count 1
          systemctl start httpd
          systemctl enable httpd
  MorgoSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enables SSH and HTTP" # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"

Outputs:
  MorgoURL:
    Description: URL of the Roman Numerals Converter
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt MorgoInstance.PublicDnsName
  